services:
  - type: web
    name: yelhaerp
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
