export interface ModuleHelpContent {
  title: string
  description: string
  features: string[]
  tips: string[]
}

export const MODULE_HELP: Record<string, Record<'fr' | 'ar' | 'en', ModuleHelpContent>> = {
  dashboard: {
    fr: { title: 'Tableau de bord', description: 'Vue synthétique de toute votre activité en temps réel.', features: ['KPIs clés de votre entreprise', 'Alertes importantes', 'Raccourcis rapides vers les modules'], tips: ['Personnalisez les modules actifs dans Paramètres → Modules', 'Les chiffres se mettent à jour automatiquement'] },
    ar: { title: 'لوحة التحكم', description: 'نظرة شاملة على نشاطك التجاري في الوقت الفعلي.', features: ['مؤشرات الأداء الرئيسية', 'التنبيهات المهمة', 'روابط سريعة للوحدات'], tips: ['خصّص الوحدات النشطة في الإعدادات → الوحدات'] },
    en: { title: 'Dashboard', description: 'A real-time overview of all your business activity.', features: ['Key business KPIs', 'Important alerts', 'Quick links to modules'], tips: ['Customize active modules in Settings → Modules'] },
  },
  invoices: {
    fr: { title: 'Factures', description: 'Créez, envoyez et suivez toutes vos factures de vente. Gérez les paiements partiels, les avoirs et les relances.', features: ['Création de factures avec TVA algérienne', 'Envoi par email au client', 'Suivi des paiements (payé, partiel, impayé)', 'Génération de PDF professionnel', 'Paiement en ligne via Chargily Pay', 'Avoirs (notes de crédit)', 'Portail client pour consultation'], tips: ['Utilisez les devis pour transformer facilement en facture', 'Configurez votre numérotation dans Paramètres', 'Le portail client permet au client de voir ses factures sans compte'] },
    ar: { title: 'الفواتير', description: 'أنشئ وأرسل وتابع جميع فواتير البيع. أدر المدفوعات الجزئية وإشعارات الدائنية والتذكيرات.', features: ['إنشاء فواتير مع ضريبة القيمة المضافة الجزائرية', 'الإرسال بالبريد الإلكتروني للعميل', 'متابعة المدفوعات', 'توليد PDF احترافي', 'الدفع عبر الإنترنت عبر Chargily Pay'], tips: ['استخدم عروض الأسعار للتحويل السهل إلى فاتورة'] },
    en: { title: 'Invoices', description: 'Create, send and track all your sales invoices. Manage partial payments, credit notes and reminders.', features: ['Invoice creation with Algerian VAT', 'Email delivery to client', 'Payment tracking (paid, partial, unpaid)', 'Professional PDF generation', 'Online payment via Chargily Pay', 'Credit notes', 'Client portal'], tips: ['Use quotes to easily convert to invoice', 'Configure your numbering in Settings'] },
  },
  quotes: {
    fr: { title: 'Devis', description: 'Créez des devis professionnels, envoyez-les à vos clients et convertissez-les en factures en un clic.', features: ['Devis avec validité configurable', 'Envoi par email avec lien de validation', 'Conversion en facture en 1 clic', 'Suivi des devis (brouillon, envoyé, accepté, refusé, expiré)', 'PDF professionnel'], tips: ['Configurez la durée de validité par défaut dans Paramètres', 'Le client peut accepter le devis depuis le portail sans compte'] },
    ar: { title: 'عروض الأسعار', description: 'أنشئ عروض أسعار احترافية وحوّلها إلى فواتير بنقرة واحدة.', features: ['عروض أسعار مع صلاحية قابلة للتكوين', 'تحويل إلى فاتورة بنقرة واحدة', 'تتبع الحالة'], tips: ['يمكن للعميل قبول عرض الأسعار من البوابة'] },
    en: { title: 'Quotes', description: 'Create professional quotes and convert them to invoices in one click.', features: ['Configurable validity period', 'One-click conversion to invoice', 'Status tracking (draft, sent, accepted, declined, expired)', 'Professional PDF'], tips: ['Client can accept quote from portal without an account'] },
  },
  clients: {
    fr: { title: 'Clients', description: 'Gérez votre base clients : coordonnées, historique de facturation, soldes, et portail client.', features: ['Fiche client complète (NIF, NIS, RC, adresse, wilaya)', 'Historique des factures et devis', 'Solde client en temps réel', 'Portail client sécurisé (lien à partager)', 'Import en masse depuis CSV'], tips: ['Le portail client permet à votre client de voir toutes ses factures et devis en ligne'] },
    ar: { title: 'العملاء', description: 'أدر قاعدة عملائك: معلومات الاتصال، سجل الفوترة، الأرصدة وبوابة العملاء.', features: ['ملف عميل كامل', 'سجل الفواتير وعروض الأسعار', 'رصيد العميل في الوقت الفعلي', 'بوابة عملاء آمنة'], tips: [] },
    en: { title: 'Clients', description: 'Manage your client base: contact details, billing history, balances, and client portal.', features: ['Complete client profile (NIF, NIS, RC, address, wilaya)', 'Invoice and quote history', 'Real-time client balance', 'Secure client portal'], tips: ['The client portal lets your client view all their invoices and quotes online'] },
  },
  crm: {
    fr: { title: 'CRM', description: 'Suivez votre pipeline commercial : leads, opportunités, et relances automatiques.', features: ['Pipeline Kanban visuel', 'Gestion des leads et opportunités', 'Affectation à des commerciaux', 'Suivi des activités (appels, emails, RDV)', "Conversion d'un lead en client"], tips: ['Faites glisser les cartes dans le Kanban pour changer le statut', 'Convertissez un lead gagné en client avec un seul clic'] },
    ar: { title: 'إدارة علاقات العملاء', description: 'تتبع خط مبيعاتك: العملاء المحتملون والفرص والمتابعات.', features: ['لوحة Kanban مرئية', 'إدارة العملاء المحتملين', 'تحويل العميل المحتمل إلى عميل'], tips: [] },
    en: { title: 'CRM', description: 'Track your sales pipeline: leads, opportunities, and follow-ups.', features: ['Visual Kanban pipeline', 'Lead and opportunity management', 'Team assignment', 'Activity tracking', 'Lead to client conversion'], tips: ['Drag cards in the Kanban to change status'] },
  },
  stock: {
    fr: { title: 'Stocks', description: "Gérez vos niveaux de stock, mouvements d'entrée/sortie, alertes de rupture et entrepôts.", features: ['Suivi des quantités en temps réel par entrepôt', 'Alertes de stock minimum configurable', 'Historique de tous les mouvements (entrées, sorties, ajustements)', 'Gestion multi-entrepôts', 'Lien automatique avec les achats et les ventes', 'Inventaire et corrections de stock'], tips: ['Définissez un stock minimum pour chaque produit pour recevoir des alertes', 'Les ventes et achats mettent le stock à jour automatiquement'] },
    ar: { title: 'المخزون', description: 'أدر مستويات مخزونك وحركات الدخول/الخروج وتنبيهات النفاد والمستودعات.', features: ['تتبع الكميات في الوقت الفعلي', 'تنبيهات المخزون الأدنى', 'سجل جميع الحركات', 'إدارة متعددة المستودعات'], tips: ['حدد حداً أدنى للمخزون لكل منتج لتلقي التنبيهات'] },
    en: { title: 'Stock', description: 'Manage your stock levels, in/out movements, low-stock alerts and warehouses.', features: ['Real-time quantity tracking per warehouse', 'Configurable minimum stock alerts', 'Full movement history', 'Multi-warehouse management', 'Auto-linked to purchases and sales'], tips: ['Set a minimum stock per product to receive alerts', 'Sales and purchases update stock automatically'] },
  },
  purchases: {
    fr: { title: 'Achats', description: 'Gérez vos commandes fournisseurs, réceptions de marchandises et factures fournisseur.', features: ['Création de bons de commande fournisseur', 'Réception partielle ou complète des marchandises', 'Mise à jour automatique du stock à la réception', 'Factures fournisseur et rapprochement', 'Suivi des délais de livraison'], tips: ['Une commande fournisseur peut être reçue en plusieurs fois', 'La réception met à jour le stock automatiquement'] },
    ar: { title: 'المشتريات', description: 'أدر طلبات الموردين واستلام البضائع وفواتير الموردين.', features: ['إنشاء أوامر شراء', 'استلام جزئي أو كامل', 'تحديث تلقائي للمخزون عند الاستلام'], tips: [] },
    en: { title: 'Purchases', description: 'Manage supplier orders, goods receipts and supplier invoices.', features: ['Purchase order creation', 'Partial or full goods receipt', 'Auto stock update on receipt', 'Supplier invoice and matching'], tips: ['A purchase order can be received in multiple deliveries'] },
  },
  hr: {
    fr: { title: 'Ressources Humaines', description: 'Gérez vos employés, congés, évaluations de performance et organigramme.', features: ['Fiche employé complète', 'Gestion des demandes de congés (validation workflow)', 'Solde de congés automatique', 'Évaluations annuelles', 'Organigramme interactif', 'Recrutement (offres et candidats)'], tips: ["Les congés validés ici sont liés au module Paie automatiquement", "L'organigramme se construit automatiquement selon les relations hiérarchiques"] },
    ar: { title: 'الموارد البشرية', description: 'أدر موظفيك وإجازاتهم وتقييمات الأداء والهيكل التنظيمي.', features: ['ملف موظف كامل', 'إدارة طلبات الإجازات', 'التقييمات السنوية', 'المخطط التنظيمي'], tips: [] },
    en: { title: 'Human Resources', description: 'Manage your employees, leave requests, performance reviews and org chart.', features: ['Complete employee profile', 'Leave request workflow', 'Automatic leave balance', 'Performance reviews', 'Interactive org chart', 'Recruitment'], tips: ['Approved leaves are automatically linked to Payroll'] },
  },
  payroll: {
    fr: { title: 'Paie', description: "Calculez les bulletins de paie conformes à la législation algérienne (IRG progressif, CNAS salarié et patronal).", features: ['Calcul automatique IRG (barème progressif 2026)', 'CNAS salarié (9%) et patronal (26%)', 'Bulletins de paie PDF officiels', 'Historique des paiements par employé', 'Export pour déclaration CNAS/DGI'], tips: ['Les taux IRG et CNAS sont mis à jour selon la législation en vigueur', 'Le bulletin de paie est générable en PDF pour chaque employé'] },
    ar: { title: 'كشف الرواتب', description: 'احسب كشوف الرواتب وفق القانون الجزائري (IRG التدريجي، CNAS).', features: ['حساب تلقائي IRG', 'CNAS للموظف (9%) وصاحب العمل (26%)', 'ورقة راتب PDF رسمية'], tips: [] },
    en: { title: 'Payroll', description: 'Calculate payslips compliant with Algerian legislation (progressive IRG, employee and employer CNAS).', features: ['Auto IRG calculation (2026 progressive scale)', 'Employee CNAS (9%) and employer (26%)', 'Official PDF payslips', 'Payment history per employee'], tips: [] },
  },
  accounting: {
    fr: { title: 'Comptabilité', description: 'Journal comptable selon le PCN (Plan Comptable National) algérien, avec lettrage et rapprochement bancaire.', features: ['Journal des écritures (PCN algérien)', 'Grand livre par compte', 'Balance générale', 'Bilan et compte de résultat', 'Lettrage des comptes', 'Rapprochement bancaire'], tips: ['Le PCN algérien est pré-configuré avec tous les comptes standard', 'Les factures et achats génèrent des écritures automatiques si la comptabilité est activée'] },
    ar: { title: 'المحاسبة', description: 'سجل محاسبي وفق المخطط المحاسبي الوطني الجزائري مع المقاصة والتسوية البنكية.', features: ['سجل القيود المحاسبية', 'دفتر الأستاذ', 'الميزانية العمومية وحساب النتائج'], tips: [] },
    en: { title: 'Accounting', description: 'Accounting journal per the Algerian PCN (National Chart of Accounts), with matching and bank reconciliation.', features: ['Journal entries (Algerian PCN)', 'General ledger', 'Trial balance', 'Balance sheet and P&L', 'Bank reconciliation'], tips: ['PCN is pre-configured with all standard accounts'] },
  },
  projects: {
    fr: { title: 'Projets', description: "Gérez vos projets, tâches et temps passé. Facturez vos clients sur la base du temps ou du forfait.", features: ["Projets avec membres de l'équipe", 'Tâches et sous-tâches', 'Pointage du temps (timesheets)', 'Facturation au temps ou au forfait', 'Suivi budget vs réel', 'Tableau de bord projet'], tips: ['Le temps saisi peut être converti en ligne de facture automatiquement', 'Suivez le budget en temps réel pour éviter les dépassements'] },
    ar: { title: 'المشاريع', description: 'أدر مشاريعك ومهامك ووقت العمل. فوتر عملاءك بناءً على الوقت أو المبلغ الثابت.', features: ['مشاريع مع أعضاء الفريق', 'المهام والمهام الفرعية', 'تسجيل الوقت', 'الفوترة بالوقت أو بسعر ثابت'], tips: [] },
    en: { title: 'Projects', description: 'Manage your projects, tasks and time spent. Invoice clients based on time or fixed price.', features: ['Projects with team members', 'Tasks and subtasks', 'Time tracking (timesheets)', 'Time or fixed-price billing', 'Budget vs actual tracking'], tips: ['Logged time can be auto-converted to invoice lines'] },
  },
  production: {
    fr: { title: 'Production', description: "Gérez vos ordres de fabrication (OF), nomenclatures (BOM) et consommation de matières premières.", features: ['Nomenclatures produits (Bill of Materials)', 'Ordres de fabrication avec statuts', 'Consommation automatique des composants', "Suivi de l'avancement en temps réel", 'Coût de revient par OF'], tips: ["La nomenclature définit les composants et quantités nécessaires pour fabriquer un produit", "Le lancement d'un OF déduit automatiquement les composants du stock"] },
    ar: { title: 'الإنتاج', description: 'أدر أوامر التصنيع وقوائم المواد واستهلاك المواد الخام.', features: ['قوائم المواد (BOM)', 'أوامر التصنيع مع الحالات', 'الاستهلاك التلقائي للمكونات'], tips: [] },
    en: { title: 'Production', description: 'Manage manufacturing orders (MO), bills of materials (BOM) and raw material consumption.', features: ['Bills of materials (BOM)', 'Manufacturing orders with statuses', 'Auto component consumption', 'Real-time progress tracking', 'Cost per MO'], tips: ['Launching an MO automatically deducts components from stock'] },
  },
  pos: {
    fr: { title: 'Point de Vente (Caisse)', description: 'Interface de vente rapide pour les commerces physiques. Encaissez en espèces ou par paiement électronique.', features: ['Interface caisse tactile optimisée', 'Sessions de caisse avec bilan en fin de journée', 'Espèces, Chargily Pay (Edahabia/CIB)', 'Tickets thermiques (imprimante USB/Bluetooth)', 'Gestion des remises et promotions', 'Historique des ventes par session'], tips: ["Configurez votre imprimante thermique dans Paramètres → Imprimante", 'Une session de caisse doit être ouverte avant de commencer à vendre'] },
    ar: { title: 'نقطة البيع (الصندوق)', description: 'واجهة بيع سريعة للمتاجر الفعلية. اقبل الدفع نقداً أو إلكترونياً.', features: ['واجهة صندوق محسّنة باللمس', 'جلسات صندوق مع ملخص نهاية اليوم', 'نقداً، Chargily Pay', 'إيصالات حرارية'], tips: [] },
    en: { title: 'Point of Sale (POS)', description: 'Fast sales interface for physical stores. Accept cash or electronic payments.', features: ['Touch-optimized POS interface', 'Cash sessions with end-of-day summary', 'Cash, Chargily Pay (Edahabia/CIB)', 'Thermal receipts (USB/Bluetooth printer)', 'Discounts and promotions'], tips: ['Configure your thermal printer in Settings → Printer', 'A cash session must be opened before selling'] },
  },
  subscriptions: {
    fr: { title: 'Abonnements clients', description: 'Gérez les abonnements récurrents de vos propres clients. Encaissez par Chargily Pay ou virement CCP.', features: ["Plans d'abonnement personnalisables (journalier, hebdo, mensuel, trimestriel, annuel)", 'Paiement en ligne via votre propre compte Chargily', 'Paiement par virement CCP', 'Emails automatiques au client (démarrage, rappels, expiration)', 'Widget embeddable sur votre site web', 'Renouvellement automatique après paiement confirmé'], tips: ["Configurez vos clés Chargily dans Paramètres → Paiement", "Le widget permet à vos clients de s'abonner directement depuis votre site web"] },
    ar: { title: 'اشتراكات العملاء', description: 'أدر الاشتراكات المتكررة لعملائك. اقبل الدفع عبر Chargily Pay أو تحويل CCP.', features: ['خطط اشتراك قابلة للتخصيص', 'الدفع عبر الإنترنت من خلال حساب Chargily الخاص بك', 'الدفع بتحويل CCP', 'رسائل بريد إلكتروني تلقائية للعميل'], tips: [] },
    en: { title: 'Client Subscriptions', description: 'Manage recurring subscriptions for your own clients. Collect via your Chargily account or CCP transfer.', features: ['Customizable plans (daily, weekly, monthly, quarterly, annual)', 'Online payment via your Chargily account', 'CCP wire transfer payment', 'Automatic emails (start, reminders, expiry)', 'Embeddable widget for your website'], tips: ['Configure your Chargily keys in Settings → Payment'] },
  },
  tax: {
    fr: { title: 'Fiscalité (G50)', description: 'Générez automatiquement votre déclaration G50 mensuelle (TVA, CNAS, IRG) depuis vos données comptables.', features: ['Calcul automatique TVA collectée / déductible', 'Calcul CNAS et IRG à la source', 'Génération du formulaire G50 pré-rempli en PDF', 'Alertes délai (avant le 20 du mois)', 'Historique des déclarations par mois/année'], tips: ['Le G50 est dû avant le 20 de chaque mois pour le mois précédent', 'Les données sont automatiquement calculées depuis vos factures et fiches de paie'] },
    ar: { title: 'الجباية (G50)', description: 'أنشئ تلقائياً إقرار G50 الشهري (TVA، CNAS، IRG) من بياناتك المحاسبية.', features: ['حساب تلقائي لـ TVA المحصّلة / القابلة للخصم', 'حساب CNAS و IRG المستقطع', 'توليد نموذج G50 مملوء مسبقاً بصيغة PDF', 'تنبيهات المهلة (قبل 20 من الشهر)'], tips: ['G50 مستحق قبل 20 من كل شهر عن الشهر السابق'] },
    en: { title: 'Tax (G50)', description: 'Auto-generate your monthly G50 declaration (VAT, CNAS, IRG) from your accounting data.', features: ['Auto calculation of collected/deductible VAT', 'CNAS and withheld IRG calculation', 'Pre-filled G50 PDF form generation', 'Deadline alerts (before the 20th)', 'Declaration history by month/year'], tips: ['G50 is due before the 20th of each month for the previous month'] },
  },
  restaurant: {
    fr: { title: 'Restaurant', description: 'Gestion complète pour restaurants : plan de salle, commandes, cuisine (KDS), menu QR et fidélité clients.', features: ['Plan de salle interactif (tables, statuts en temps réel)', 'Commandes dine-in, emporter et livraison', 'Écran cuisine KDS (Kitchen Display System)', 'Menu digital QR scannable par les clients', 'Stock cuisine avec déduction automatique', 'Programme de fidélité avec paliers', 'Réservations de tables'], tips: ['Affichez le QR code de chaque table pour que vos clients commandent directement depuis leur téléphone', "L'écran KDS est conçu pour être affiché sur un écran dédié en cuisine"] },
    ar: { title: 'المطعم', description: 'إدارة شاملة للمطاعم: مخطط القاعة والطلبات والمطبخ (KDS) وقائمة QR وولاء العملاء.', features: ['مخطط قاعة تفاعلي', 'طلبات في المطعم والاصطحاب والتوصيل', 'شاشة مطبخ KDS', 'قائمة رقمية QR للعملاء', 'مخزون المطبخ مع خصم تلقائي', 'برنامج ولاء'], tips: [] },
    en: { title: 'Restaurant', description: 'Full restaurant management: floor plan, orders, kitchen (KDS), QR menu and customer loyalty.', features: ['Interactive floor plan (tables, real-time status)', 'Dine-in, takeaway and delivery orders', 'Kitchen Display System (KDS)', 'QR-scannable digital menu', 'Kitchen stock with auto-deduction', 'Loyalty program with tiers', 'Table reservations'], tips: ['Display the QR code on each table so customers order directly from their phone'] },
  },
  expenses: {
    fr: { title: 'Dépenses', description: "Enregistrez et validez les notes de frais et dépenses de votre entreprise.", features: ['Saisie des dépenses avec justificatif (photo)', 'Workflow de validation (soumis → approuvé → payé)', 'Catégories de dépenses personnalisables', 'Rapports par période et catégorie', 'Lien avec la comptabilité si activée'], tips: ["Les dépenses approuvées peuvent être exportées pour votre comptable", 'Joignez toujours un justificatif scanné pour faciliter la validation'] },
    ar: { title: 'المصروفات', description: 'سجّل ووافق على تقارير مصروفات شركتك.', features: ['إدخال المصروفات مع الإيصال', 'سير عمل الموافقة', 'فئات مصروفات قابلة للتخصيص'], tips: [] },
    en: { title: 'Expenses', description: 'Record and approve your company expense reports.', features: ['Expense entry with receipt (photo)', 'Approval workflow (submitted → approved → paid)', 'Customizable expense categories', 'Period and category reports'], tips: ['Attach a scanned receipt to ease approval'] },
  },
  ecommerce: {
    fr: { title: 'E-commerce', description: 'Synchronisez votre boutique en ligne (Shopify, WooCommerce) avec votre stock et facturation YelhaERP.', features: ['Synchronisation des commandes Shopify / WooCommerce', 'Mise à jour automatique des stocks', 'Génération de factures depuis les commandes e-commerce', 'Suivi des retours et remboursements'], tips: ["Configurez votre clé API Shopify dans Paramètres → Intégrations"] },
    ar: { title: 'التجارة الإلكترونية', description: 'زامن متجرك الإلكتروني (Shopify، WooCommerce) مع مخزونك وفوترتك.', features: ['مزامنة طلبات Shopify / WooCommerce', 'تحديث تلقائي للمخزون', 'توليد فواتير من طلبات التجارة الإلكترونية'], tips: [] },
    en: { title: 'E-Commerce', description: 'Sync your online store (Shopify, WooCommerce) with your stock and billing.', features: ['Shopify / WooCommerce order sync', 'Auto stock update', 'Invoice generation from e-commerce orders', 'Returns and refunds tracking'], tips: ['Configure your Shopify API key in Settings → Integrations'] },
  },
}
