// Plan Comptable National (PCN) algérien — comptes standards
// Source : PCN algérien révisé (Journal Officiel n°57 du 26/11/2009)

import type { AccountType } from '@prisma/client'

interface PCNAccount {
  code: string
  name: string
  class: number
  type: AccountType
  parentCode?: string
}

export const PCN_ACCOUNTS: PCNAccount[] = [
  // ── Classe 1 : Capitaux ──────────────────────────────────────
  { code: '10', name: 'Capital et réserves', class: 1, type: 'PASSIF' },
  { code: '101', name: 'Capital social', class: 1, type: 'PASSIF', parentCode: '10' },
  { code: '1013', name: 'Capital souscrit, appelé, versé', class: 1, type: 'PASSIF', parentCode: '101' },
  { code: '106', name: 'Réserves', class: 1, type: 'PASSIF', parentCode: '10' },
  { code: '1061', name: 'Réserve légale', class: 1, type: 'PASSIF', parentCode: '106' },
  { code: '1068', name: 'Autres réserves', class: 1, type: 'PASSIF', parentCode: '106' },
  { code: '11', name: 'Report à nouveau', class: 1, type: 'PASSIF' },
  { code: '110', name: 'Report à nouveau solde créditeur', class: 1, type: 'PASSIF', parentCode: '11' },
  { code: '119', name: 'Report à nouveau solde débiteur', class: 1, type: 'PASSIF', parentCode: '11' },
  { code: '12', name: 'Résultat net de l\'exercice', class: 1, type: 'PASSIF' },
  { code: '120', name: 'Résultat net de l\'exercice — bénéfice', class: 1, type: 'PASSIF', parentCode: '12' },
  { code: '129', name: 'Résultat net de l\'exercice — perte', class: 1, type: 'PASSIF', parentCode: '12' },
  { code: '13', name: 'Produit des émissions de titres', class: 1, type: 'PASSIF' },
  { code: '16', name: 'Emprunts et dettes assimilées', class: 1, type: 'PASSIF' },
  { code: '164', name: 'Emprunts auprès des établissements de crédit', class: 1, type: 'PASSIF', parentCode: '16' },
  { code: '168', name: 'Autres emprunts et dettes assimilées', class: 1, type: 'PASSIF', parentCode: '16' },

  // ── Classe 2 : Immobilisations ───────────────────────────────
  { code: '20', name: 'Immobilisations incorporelles', class: 2, type: 'ACTIF' },
  { code: '201', name: 'Frais de développement', class: 2, type: 'ACTIF', parentCode: '20' },
  { code: '202', name: 'Concessions, brevets, licences, marques', class: 2, type: 'ACTIF', parentCode: '20' },
  { code: '205', name: 'Fonds commercial', class: 2, type: 'ACTIF', parentCode: '20' },
  { code: '21', name: 'Immobilisations corporelles', class: 2, type: 'ACTIF' },
  { code: '211', name: 'Terrains', class: 2, type: 'ACTIF', parentCode: '21' },
  { code: '212', name: 'Constructions', class: 2, type: 'ACTIF', parentCode: '21' },
  { code: '213', name: 'Installations techniques, matériel', class: 2, type: 'ACTIF', parentCode: '21' },
  { code: '215', name: 'Matériel de transport', class: 2, type: 'ACTIF', parentCode: '21' },
  { code: '218', name: 'Autres immobilisations corporelles', class: 2, type: 'ACTIF', parentCode: '21' },
  { code: '28', name: 'Amortissements des immobilisations', class: 2, type: 'ACTIF' },
  { code: '281', name: 'Amortissements des immo. incorporelles', class: 2, type: 'ACTIF', parentCode: '28' },
  { code: '282', name: 'Amortissements des immo. corporelles', class: 2, type: 'ACTIF', parentCode: '28' },

  // ── Classe 3 : Stocks ────────────────────────────────────────
  { code: '30', name: 'Stocks de marchandises', class: 3, type: 'ACTIF' },
  { code: '300', name: 'Marchandises', class: 3, type: 'ACTIF', parentCode: '30' },
  { code: '31', name: 'Matières premières et fournitures', class: 3, type: 'ACTIF' },
  { code: '310', name: 'Matières premières', class: 3, type: 'ACTIF', parentCode: '31' },
  { code: '32', name: 'Autres approvisionnements', class: 3, type: 'ACTIF' },
  { code: '35', name: 'Stocks de produits', class: 3, type: 'ACTIF' },
  { code: '350', name: 'Produits intermédiaires', class: 3, type: 'ACTIF', parentCode: '35' },
  { code: '355', name: 'Produits finis', class: 3, type: 'ACTIF', parentCode: '35' },
  { code: '37', name: 'Stocks en cours de route', class: 3, type: 'ACTIF' },

  // ── Classe 4 : Tiers ─────────────────────────────────────────
  { code: '40', name: 'Fournisseurs et comptes rattachés', class: 4, type: 'PASSIF' },
  { code: '401', name: 'Fournisseurs', class: 4, type: 'PASSIF', parentCode: '40' },
  { code: '403', name: 'Fournisseurs — Effets à payer', class: 4, type: 'PASSIF', parentCode: '40' },
  { code: '404', name: 'Fournisseurs d\'immobilisations', class: 4, type: 'PASSIF', parentCode: '40' },
  { code: '408', name: 'Fournisseurs — Factures non parvenues', class: 4, type: 'PASSIF', parentCode: '40' },
  { code: '41', name: 'Clients et comptes rattachés', class: 4, type: 'ACTIF' },
  { code: '411', name: 'Clients', class: 4, type: 'ACTIF', parentCode: '41' },
  { code: '413', name: 'Clients — Effets à recevoir', class: 4, type: 'ACTIF', parentCode: '41' },
  { code: '418', name: 'Clients — Produits non encore facturés', class: 4, type: 'ACTIF', parentCode: '41' },
  { code: '42', name: 'Personnel et comptes rattachés', class: 4, type: 'PASSIF' },
  { code: '421', name: 'Personnel — Rémunérations dues', class: 4, type: 'PASSIF', parentCode: '42' },
  { code: '425', name: 'Personnel — Avances et acomptes', class: 4, type: 'ACTIF', parentCode: '42' },
  { code: '43', name: 'Organismes sociaux', class: 4, type: 'PASSIF' },
  { code: '430', name: 'Sécurité sociale', class: 4, type: 'PASSIF', parentCode: '43' },
  { code: '431', name: 'CNAS', class: 4, type: 'PASSIF', parentCode: '43' },
  { code: '44', name: 'État et collectivités publiques', class: 4, type: 'PASSIF' },
  { code: '441', name: 'État — Subventions à recevoir', class: 4, type: 'ACTIF', parentCode: '44' },
  { code: '442', name: 'État — Impôts et taxes à payer', class: 4, type: 'PASSIF', parentCode: '44' },
  { code: '444', name: 'État — IBS à payer', class: 4, type: 'PASSIF', parentCode: '44' },
  { code: '445', name: 'État — TVA', class: 4, type: 'PASSIF' },
  { code: '4452', name: 'TVA récupérable sur achats', class: 4, type: 'ACTIF', parentCode: '445' },
  { code: '4456', name: 'TVA collectée', class: 4, type: 'PASSIF', parentCode: '445' },
  { code: '4457', name: 'TVA à décaisser', class: 4, type: 'PASSIF', parentCode: '445' },
  { code: '45', name: 'Groupe et associés', class: 4, type: 'ACTIF' },
  { code: '46', name: 'Débiteurs divers et créditeurs divers', class: 4, type: 'ACTIF' },
  { code: '461', name: 'Débiteurs divers', class: 4, type: 'ACTIF', parentCode: '46' },
  { code: '467', name: 'Autres comptes créditeurs', class: 4, type: 'PASSIF', parentCode: '46' },
  { code: '48', name: 'Comptes de régularisation', class: 4, type: 'ACTIF' },
  { code: '486', name: 'Charges constatées d\'avance', class: 4, type: 'ACTIF', parentCode: '48' },
  { code: '487', name: 'Produits constatés d\'avance', class: 4, type: 'PASSIF', parentCode: '48' },

  // ── Classe 5 : Comptes financiers ────────────────────────────
  { code: '51', name: 'Banques, établissements financiers', class: 5, type: 'ACTIF' },
  { code: '512', name: 'Banques', class: 5, type: 'ACTIF', parentCode: '51' },
  { code: '514', name: 'Chèques postaux', class: 5, type: 'ACTIF', parentCode: '51' },
  { code: '52', name: 'Instruments financiers', class: 5, type: 'ACTIF' },
  { code: '53', name: 'Caisse', class: 5, type: 'ACTIF' },
  { code: '531', name: 'Caisse siège social', class: 5, type: 'ACTIF', parentCode: '53' },
  { code: '532', name: 'Caisse succursales', class: 5, type: 'ACTIF', parentCode: '53' },
  { code: '54', name: 'Régies d\'avances et accréditifs', class: 5, type: 'ACTIF' },

  // ── Classe 6 : Charges ───────────────────────────────────────
  { code: '60', name: 'Achats et variations de stocks', class: 6, type: 'CHARGE' },
  { code: '600', name: 'Achats de marchandises', class: 6, type: 'CHARGE', parentCode: '60' },
  { code: '601', name: 'Matières premières', class: 6, type: 'CHARGE', parentCode: '60' },
  { code: '605', name: 'Autres approvisionnements', class: 6, type: 'CHARGE', parentCode: '60' },
  { code: '61', name: 'Services extérieurs', class: 6, type: 'CHARGE' },
  { code: '613', name: 'Locations', class: 6, type: 'CHARGE', parentCode: '61' },
  { code: '614', name: 'Charges locatives', class: 6, type: 'CHARGE', parentCode: '61' },
  { code: '615', name: 'Entretien et réparations', class: 6, type: 'CHARGE', parentCode: '61' },
  { code: '616', name: 'Primes d\'assurances', class: 6, type: 'CHARGE', parentCode: '61' },
  { code: '618', name: 'Divers', class: 6, type: 'CHARGE', parentCode: '61' },
  { code: '62', name: 'Autres services extérieurs', class: 6, type: 'CHARGE' },
  { code: '621', name: 'Personnel extérieur à l\'entreprise', class: 6, type: 'CHARGE', parentCode: '62' },
  { code: '622', name: 'Rémunérations d\'intermédiaires', class: 6, type: 'CHARGE', parentCode: '62' },
  { code: '623', name: 'Publicité, publications, relations publiques', class: 6, type: 'CHARGE', parentCode: '62' },
  { code: '624', name: 'Transports de biens et transports collectifs', class: 6, type: 'CHARGE', parentCode: '62' },
  { code: '625', name: 'Déplacements, missions et réceptions', class: 6, type: 'CHARGE', parentCode: '62' },
  { code: '626', name: 'Frais postaux et de télécommunications', class: 6, type: 'CHARGE', parentCode: '62' },
  { code: '63', name: 'Charges de personnel', class: 6, type: 'CHARGE' },
  { code: '631', name: 'Rémunérations du personnel', class: 6, type: 'CHARGE', parentCode: '63' },
  { code: '632', name: 'Rémunérations de l\'exploitant', class: 6, type: 'CHARGE', parentCode: '63' },
  { code: '635', name: 'Cotisations aux organismes sociaux', class: 6, type: 'CHARGE', parentCode: '63' },
  { code: '64', name: 'Impôts, taxes et versements assimilés', class: 6, type: 'CHARGE' },
  { code: '641', name: 'Impôts et taxes locaux', class: 6, type: 'CHARGE', parentCode: '64' },
  { code: '645', name: 'Taxes sur le chiffre d\'affaires non récupérables', class: 6, type: 'CHARGE', parentCode: '64' },
  { code: '65', name: 'Autres charges de gestion courante', class: 6, type: 'CHARGE' },
  { code: '66', name: 'Charges financières', class: 6, type: 'CHARGE' },
  { code: '661', name: 'Charges d\'intérêts', class: 6, type: 'CHARGE', parentCode: '66' },
  { code: '668', name: 'Autres charges financières', class: 6, type: 'CHARGE', parentCode: '66' },
  { code: '67', name: 'Éléments extraordinaires — charges', class: 6, type: 'CHARGE' },
  { code: '68', name: 'Dotations aux amortissements et provisions', class: 6, type: 'CHARGE' },
  { code: '681', name: 'Dotations aux amortissements, dépréciations', class: 6, type: 'CHARGE', parentCode: '68' },
  { code: '685', name: 'Dotations aux provisions', class: 6, type: 'CHARGE', parentCode: '68' },

  // ── Classe 7 : Produits ──────────────────────────────────────
  { code: '70', name: 'Ventes de marchandises', class: 7, type: 'PRODUIT' },
  { code: '700', name: 'Ventes de marchandises', class: 7, type: 'PRODUIT', parentCode: '70' },
  { code: '701', name: 'Ventes de produits finis', class: 7, type: 'PRODUIT', parentCode: '70' },
  { code: '704', name: 'Travaux', class: 7, type: 'PRODUIT', parentCode: '70' },
  { code: '706', name: 'Prestations de services', class: 7, type: 'PRODUIT', parentCode: '70' },
  { code: '707', name: 'Ventes de marchandises', class: 7, type: 'PRODUIT', parentCode: '70' },
  { code: '708', name: 'Produits des activités annexes', class: 7, type: 'PRODUIT', parentCode: '70' },
  { code: '71', name: 'Production stockée', class: 7, type: 'PRODUIT' },
  { code: '72', name: 'Production immobilisée', class: 7, type: 'PRODUIT' },
  { code: '74', name: 'Subventions d\'exploitation', class: 7, type: 'PRODUIT' },
  { code: '75', name: 'Autres produits de gestion courante', class: 7, type: 'PRODUIT' },
  { code: '76', name: 'Produits financiers', class: 7, type: 'PRODUIT' },
  { code: '761', name: 'Produits de participations', class: 7, type: 'PRODUIT', parentCode: '76' },
  { code: '762', name: 'Produits des autres immobilisations financières', class: 7, type: 'PRODUIT', parentCode: '76' },
  { code: '763', name: 'Revenus des autres créances', class: 7, type: 'PRODUIT', parentCode: '76' },
  { code: '765', name: 'Escomptes obtenus', class: 7, type: 'PRODUIT', parentCode: '76' },
  { code: '768', name: 'Autres produits financiers', class: 7, type: 'PRODUIT', parentCode: '76' },
  { code: '77', name: 'Éléments extraordinaires — produits', class: 7, type: 'PRODUIT' },
  { code: '78', name: 'Reprises sur amortissements et provisions', class: 7, type: 'PRODUIT' },
]

export const CLASS_LABELS: Record<number, string> = {
  1: 'Classe 1 — Capitaux',
  2: 'Classe 2 — Immobilisations',
  3: 'Classe 3 — Stocks',
  4: 'Classe 4 — Tiers',
  5: 'Classe 5 — Comptes financiers',
  6: 'Classe 6 — Charges',
  7: 'Classe 7 — Produits',
}
